# Hi, from Rauhmel Fox, CEO, WHOmentors.com, Inc.
# These are the settings for JumpStarter Code™ a derivative of the Ruby on Rails open source SelfStarter crowdfunding boilerplate.
# This is more tidy than changing the HTML if all you want to do is rename things and swap out images

# You should totally change the HTML and CSS though
# Checkout app/assets/stylesheets/variables.css.scss to change around the CSS quickly

# Set your project goal here - dollar amount
# NOTE: if you manually want to adjust your progress to test the site, head over to the Order model (app/models/order.rb)
project_goal: 1500000

# If you want to edit the FAQ, head over to app/views/preorder/homepage/_faqs.html.erb

# This'll be both the page title (<title></title>) and the name in the header
product_name: "skihlz™"

# This will be used in sentences like Hooray You've just reserved product_description
product_description: "skihlz branded shoes for teen athletes"

# An image showcasing your product -- it'll show up when you pin your product
# It should be in app/assets/images
product_image_path: "my-product-image.png"

# The message on the preorder page, Lockitron's is ""
value_proposition: "Rauhmel Fox, CEO, WHOmentors.com, Inc."

# YouTube or Vimeo Video URL (The embed URL, without the query string options)
# Replace /embed/ in your video url path with /v/ for video playback to work.
video_embed_url: "https://www.youtube.com/embed/x6lh6rU_yRA"

# If set to true, then the image at "/assets/video_placeholder.png" will be shown in place of the youtube
# video.  When the user clicks it, the vid will replace the image and start playing.
#
# NOTE: you can set this to false, and no image will be use - first frame of the video will be displayed
#
# NOTE: this only works for youtube video at the moment.  If it's not for youtube, then just leave this property blank
use_video_placeholder: false

# Amazon settings -- you'll need an Amazon Payments account, sign up here --> http://bit.ly/SGksTv

# To find your access key and secret key, head over to here --> http://bit.ly/R4I4ky (Follow that guide in the Seller Central page)
amazon_access_key: ""
amazon_secret_key: ""
price: 	25.00

# if use_payment_options is set to true, then a set of radio buttons will be displayed with various payment options.
# There is a PaymentOption model for storing info about payment options.  To set up your payment options you should
# put code in seeds.rb, then run rake db:seed
use_payment_options: true

payment_description: "Your contribution goes to support and develop teen amateur athletes for national or international competition in sports like the International Children's Games and the Youth Olympic Games. 26 U.S.C. §501(c)(3) and §501(j)(2)."

# Amazon limits how much we can charge people with their Multi-Use tokens.
# You probably should add some leeway to account for international shipping
# this value will be added to the price to create a charge limit
charge_limit: 35.00

# Stats settings

primary_stat: "backers"
# This'll show up in the tweet as, "I'm backer number ..."
primary_stat_verb: 'backer'

# The 2nd call to action button, towards the middle-ish of the page
middle_reserve_text: "Donate Today"

# When the project should end
expiration_date: <%= DateTime.now + 60 %>

# Text to show inside the progress bar, when the goal reaches/exceeds 100%
progress_text: "Implemented"

# Call to action section

ships: "1 pair of free shoes for a teen"

call_to_action: "Donate Today!"

price_human: "$25 contribution per pair."

# The paragraph below the price. You'd probably say something about how you're not going to charge them before it ships (so it's less risky).
dont_give_them_a_reason_to_say_no: "Goal: 60,000 shoes to entities like International Children's Games and Youth Olympic Games"

# Social Stuff
facebook_app_id: "1405453156376400"
# Tweets are prefixed with "I'm #{Settings.primary_stat} number X for #{Settings.product_name}"
# Maybe mention something about your product vision -- e.g. "to replace keys with my phone"
tweet_text: "I donated $25 or more to give @skihlz @skihlzshoes to a teen athlete!"

# Google Analytics
google_id: "UA-48283012-1"

# If you want to change the images for the key points 
# They're in app/assets/images/#{pointer_number}-background.png
# So, the first key point, it's at app/assets/images/1-background.png
# Alternatively, change it up in app/assets/stylesheets/homepage/key_points.css.scss
